# Generated by Django 3.2.10 on 2021-12-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djpaypal', '0014_auto_20211222_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookevent',
            name='resource_version',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
    ]
